"""Add unit_id to recipe_items

Revision ID: 68c8018a5d8d
Revises: 02ff1b9bb4c0
Create Date: 2026-04-03 23:07:50.892531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c8018a5d8d'
down_revision: Union[str, Sequence[str], None] = '02ff1b9bb4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_items', sa.Column('unit_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'recipe_items', 'units', ['unit_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_items', type_='foreignkey')
    op.drop_column('recipe_items', 'unit_id')
    # ### end Alembic commands ###
